# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eK-ujTrRNd-CLnT-e6-MZtEjBssolec6
"""

# ==========================================
# AI-Based Predictive Maintenance using SVM
# ==========================================

# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, ConfusionMatrixDisplay

# -----------------------------------
# Upload Dataset
# -----------------------------------
print("Upload your AI4I dataset (.csv)")
uploaded = files.upload()

# Get uploaded filename automatically
filename = list(uploaded.keys())[0]

# Load Dataset
data = pd.read_csv(filename)

print("\nDataset Loaded Successfully!")
print(data.head())

print("\nDataset Information")
print(data.info())

print("\nSummary Statistics")
print(data.describe())

# -----------------------------------
# Remove unnecessary columns
# -----------------------------------
data.drop(columns=['UDI', 'Product ID'], inplace=True)

# -----------------------------------
# Convert Machine Type into Numbers
# -----------------------------------
encoder = LabelEncoder()
data['Type'] = encoder.fit_transform(data['Type'])

# -----------------------------------
# Features and Target
# -----------------------------------
X = data[['Type',
          'Air temperature [K]',
          'Process temperature [K]',
          'Rotational speed [rpm]',
          'Torque [Nm]',
          'Tool wear [min]']]

y = data['Machine failure']

# -----------------------------------
# Split Dataset
# -----------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# -----------------------------------
# Feature Scaling
# -----------------------------------
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# -----------------------------------
# Train SVM Model
# -----------------------------------
svm = SVC(kernel='rbf', C=1.0, gamma='scale')

svm.fit(X_train, y_train)

print("\nSVM Model Trained Successfully!")

# -----------------------------------
# Prediction
# -----------------------------------
y_pred = svm.predict(X_test)

# -----------------------------------
# Accuracy
# -----------------------------------
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy :", accuracy)

# -----------------------------------
# Confusion Matrix
# -----------------------------------
cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix")
print(cm)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

# -----------------------------------
# Classification Report
# -----------------------------------
print("\nClassification Report")
print(classification_report(y_test, y_pred))

# -----------------------------------
# Visualization
# -----------------------------------
plt.figure(figsize=(8,6))

plt.scatter(
    data['Air temperature [K]'],
    data['Process temperature [K]'],
    c=data['Machine failure'],
    cmap='coolwarm'
)

plt.xlabel("Air Temperature (K)")
plt.ylabel("Process Temperature (K)")
plt.title("Machine Failure Distribution")
plt.colorbar(label="Machine Failure")
plt.show()

# -----------------------------------
# Predict New Machine
# -----------------------------------
print("\nPredict New Machine")

print("Machine Type:")
print("L = Low")
print("M = Medium")
print("H = High")

machine_type = input("Enter Machine Type (L/M/H): ").upper()

type_dict = {
    'L':0,
    'M':1,
    'H':2
}

air_temp = float(input("Air Temperature (K): "))
process_temp = float(input("Process Temperature (K): "))
rpm = float(input("Rotational Speed (rpm): "))
torque = float(input("Torque (Nm): "))
tool_wear = float(input("Tool Wear (min): "))

new_data = [[
    type_dict[machine_type],
    air_temp,
    process_temp,
    rpm,
    torque,
    tool_wear
]]

new_data = scaler.transform(new_data)

prediction = svm.predict(new_data)

if prediction[0] == 0:
    print("\nPrediction: Healthy Machine")
else:
    print("\nPrediction: Machine Failure")

